FROM node:18 as builder

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm i -g @nestjs/cli
RUN npm install

COPY . .

RUN npm run build

FROM node:18

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/.env.example ./.env

EXPOSE ${PORT}

CMD ["npm", "run", "start:prisma"]
