name: rs-library-dev
services:
  postgres-service:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PG_PSW}
    networks:
      - rs-net
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend-service:
    container_name: backend
    build:
      context: .
    command: sh -c "cd /app/ && npm install && npm run start:dev"
    environment:
      - HOST=backend
      - PORT=${PORT}
      - PG_HOST=postgres
      - PG_PORT=${PG_PORT}
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PSW=${PG_PSW}
    networks:
      - rs-net
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - postgres-service
networks:
  rs-net: {}
volumes:
  postgres-data: {}
