name: rs-library-dev
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PG_PSW}
    networks:
      - server
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: .
    command: sh -c "cd /app/ && npm install && npm run start:dev"
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - PG_HOST=postgres
      - PG_PORT=${PG_PORT}
      - PG_DB=rs-library
      - PG_USER=postgres
      - PG_PSW=${PG_PSW}
    networks:
      - server
      - client
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - postgres
networks:
  client: {}
  server: {}
volumes:
  postgres-data: {}
